#!/usr/bin/env bash
platform=`uname`
if [[ $platform == 'Linux' ]]; then
  \cp src/main/resources/default-development-burin-linux.properties src/main/resources/default.properties
elif [[ $platform == 'Darwin' ]]; then
  \cp src/main/resources/default-development-burin-osx.properties src/main/resources/default.properties
fi

## Deric's tests
#export TEST_ENV=development && mvn clean test -e -Dtest=TestU*801AmIEligibleTs*

## Run single test only
#export TEST_ENV=development && mvn clean test -e -Dtest=TestUs801AmIEligibleTs8

## Run test with alert example
#export TEST_ENV=development && mvn clean test -e -Dtest=TestWorkflowMPP10

#export TEST_ENV=development && mvn clean test -X -e -Dtest=TestWorkFlowxx8a*

## Run test with alert example
# export TEST_ENV=development && xvfb-run mvn clean test -X -e -Dtest=Test1234UswdsEdwosbPartnership
#export TEST_ENV=development && mvn clean test -e -Dtest=Test1234UswdsEdwosbCorporation*

## Deepa's tests
#export TEST_ENV=development && mvn clean test -e -Dtest=TestWorkflowEDWOSB06*

## Run test and see if we can handle the alert properly
export TEST_ENV=development && xvfb-run mvn clean test -e -Dtest=TestSimpleLogin
